In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# Example to verify whether the numpy installed
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [5]:
# Numpy
# Creating Array

import numpy as np
 
arr1 = np.array([10,15,16,17,18])
print(arr1)

[10 15 16 17 18]


In [10]:
arr2 = np.array([[43, 56,54],
                [32,31,22],
                [66,68,88]])
 
print(arr2)

[[43 56 54]
 [32 31 22]
 [66 68 88]]


In [11]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
zeros = np.ones((3,4))
print(zeros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# O 10 20 WITH INTERVAL OF 2
# 0, 2, 4, 6, 8, 10
rng = np.arange(0, 10, 1.5 )
print(rng)

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [15]:
# O 10 20 WITH INTERVAL OF 2
# 0, 2, 4, 6, 8, 10
rng = np.arange(0, 10, 2 )
print(rng)

[0 2 4 6 8]


In [21]:
# Line space
# starting range , ending range, 5 (5 equal division)
linsp = np.linspace(0, 1, 6)
print(linsp)

[0.  0.2 0.4 0.6 0.8 1. ]


In [9]:
# Line space
# start , end, 5
linsp = np.linspace(0, 1, 7)
print(linsp)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [29]:
# Properties of Array
print(arr2.shape)
print(arr2.ndim)
print('size', arr2.size)
print('Dttype :', arr2.dtype)
print('Itemsize' , arr2.itemsize, 'bytes')

(3, 3)
2
size 9
Dttype : int64
Itemsize 8 bytes


In [ ]:
# Indexing, Slicing
# Index - Started from 0 (column started from 0 not from 1)

arr = np.array([[10, 20,30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
# index
print(arr[1,2])

#Revise Index
print(arr[-1,-1])
 

70
120


In [37]:
# Slicing
# start : stop , start : stop
# row , column 

print('firt 2 rows:', arr[:2, :])

firt 2 rows: [[10 20 30 40]
 [50 60 70 80]]


In [40]:
# Slicing 

print('2 Coulmns',arr[:, :2])

2 Coulmns [[ 10  20]
 [ 50  60]
 [ 90 100]]


In [48]:
# Math Operations

a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print(a + b)
print(a - b)
print(a * b)


# Scalar
print(a + 50)

# Universal Function 
print(np.sqrt(a))
print(np.abs(a))

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[ 60  70  80  90 100]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[10 20 30 40 50]


In [56]:
# Statistical Operations
# min, max, mean, median
# student exams scores: rows = students, Coulmns = Subject

scores = np.array ([[85, 92, 78, 90],
                    [70, 65, 88, 72],
                    [95, 88, 91, 97],
                    [60, 75, 82, 68]])
print(np.min(scores))
print(np.max(scores))
print(np.mean(scores))
print(np.median(scores))
print(np.std(scores).round(2))

# takes the average column
# axis = 0 -> it will take the columns
# axis = 1 -> it will take the rows

print(np.mean(scores, axis=0))
print(np.mean(scores, axis=1))

# Percentage columns
print(np.percentile(scores, 25))

60
97
81.0
83.5
11.13
[77.5  80.   84.75 81.75]
[86.25 73.75 92.75 71.25]
71.5


In [62]:
# Boolean Masking 
temps = np.array([22, 35, 18, 40, 15, 38, 27, 12, 33, 29])
print('temperatures:' , temps)

hot_city = temps > 28
print(hot_city)
print(temps[hot_city])

cold_city = temps < 28
print(cold_city)
print(temps[cold_city])

temperatures: [22 35 18 40 15 38 27 12 33 29]
[False  True False  True False  True False False  True  True]
[35 40 38 33 29]
[ True False  True False  True False  True  True False False]
[22 18 15 27 12]


In [ ]:
# Assignments Questions

In [68]:
# Create a numpy of integers from 1 to 50 (inclusive), reshape it into a 5×10 matrix
# then print its shape, data type, and the element at row 3, column 7.)

import numpy as np
arr = np.arange(1, 51)
print(arr)

print(arr.shape)
print(arr.ndim)
print('size', arr.size)
print('Dttype :', arr.dtype)
print('Itemsize' , arr.itemsize, 'bytes')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
(50,)
1
size 50
Dttype : int64
Itemsize 8 bytes
